# Generated by Django 5.2.3 on 2025-06-23 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título identificador da nota ou atividade avaliada.', max_length=255, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Descrição adicional sobre a nota ou atividade (opcional).', verbose_name='Descrição')),
                ('performance', models.TextField(blank=True, help_text='Detalhes sobre o desempenho do aluno nesta avaliação (opcional).', null=True, verbose_name='Desempenho')),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Valor numérico da nota atribuída. Use ponto para separar casas decimais (ex: 8.75).', max_digits=5, null=True, verbose_name='Nota')),
                ('weight', models.IntegerField(default=1, help_text='Peso da nota no cálculo final. Por padrão, é 1.', verbose_name='Peso')),
                ('date', models.DateField(help_text='Data em que a avaliação foi aplicada ou registrada.', verbose_name='Data')),
                ('evaluation_period', models.CharField(choices=[('livre', 'Livre'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('mensal', 'Mensal'), ('quadremestral', 'Quadremestral'), ('contínua', 'Contínua'), ('unidade', 'Por Unidade')], default='bimestral', help_text='Selecione o período de avaliação relacionado à nota.', max_length=20, verbose_name='Período de Avaliação')),
                ('attachment', models.FileField(blank=True, help_text='Arquivo opcional enviado com a nota, como provas ou atividades digitalizadas.', null=True, upload_to='note_attachments/', verbose_name='Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que esta nota foi registrada no sistema.', verbose_name='Criado em')),
                ('student', models.ForeignKey(help_text='Selecione o aluno a quem a nota pertence.', on_delete=django.db.models.deletion.CASCADE, to='school.student', verbose_name='Aluno')),
                ('subject', models.ForeignKey(blank=True, help_text='Informe a disciplina relacionada à nota. Pode ser deixado em branco se não aplicável.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.subject', verbose_name='Disciplina')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
            },
        ),
    ]
